### ISSUE TITLE
please add copyright statement

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/go-reap#4]
Copyright statement is nowhere to be found. Please consider adding something like

```
Copyright 2014-2015 HashiCorp
```

to README.
Thanks.

**Comment by sethvargo** [comment]
Hi @onlyjob 

Thank you for opening an issue. The LICENSE file contained at the root of the repo contains the rights and privileges that we grant to you. All projects under the "hashicorp" GitHub organization are copyrighted to HashiCorp or their respective authors. Thanks! :smile:
